server:
  port: 8081


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  cloud:


    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-user-service
          uri: lb://ms-user-service
          predicates:
            - Path=/user/**
        - id: ms-client-service
          uri: lb://ms-client-service
          predicates:
              - Path=/Client/**
        - id: ms-gestioncandidatos-service
          uri: lb://ms-gestioncandidatos-service
          predicates:
                - Path=/gestioncandidatos/**
        - id: ms-postulacion-service
          uri: lb://ms-postulacion-service
          predicates:
                - Path=/postulacion/**
                -
        - id: ms-empresa-service
          uri: lb://ms-empresa-service
          predicates:
            - Path=/empresa/**