server:
  port: 8081


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  cloud:


    gateway:

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**
        - id: ms-gestioncandidatos-service
          uri: lb://ms-gestioncandidatos-service
          predicates:
                - Path=/gestioncandidatos/**
        - id: ms-postulacion-service
          uri: lb://ms-postulacion-service
          predicates:
                - Path=/postulacion/**
        - id: ms-empresa-service
          uri: lb://ms-empresa-service
          predicates:
            - Path=/empresa/**
        - id: ms-gestiontrabajos-service
          uri: lb://ms-gestiontrabajos-service
          predicates:
            - Path=/trabajos/**

        