spring:
  application:
    name: ms-postulacion-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070

  mail:
    host: smtp.gmail.com
    port: 587
    username: bolsalaboralolef@gmail.com
    password: "bhprwaebvbtfobmm"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
